# Generated by Django 4.2.5 on 2023-09-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='make',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '------'), (1, 'Buick'), (2, 'Cadillac'), (3, 'Chevrolet'), (4, 'Ford'), (5, 'GMC'), (6, 'Chrysler'), (7, 'Dodge'), (8, 'Jeep'), (9, 'Lincoln'), (10, 'Tesla')], null=True, verbose_name='Make/Manufacturer'),
        ),
    ]
