# Generated by Django 4.2.5 on 2023-09-17 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapter_3', '0002_vehiclemodel_make'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='vehicle',
            new_name='vehicles',
        ),
    ]
